In [10]:
import pandas as pd
import numpy as np

In [6]:
prices_a = np.array([8.7, 8.9, 8.71])

In [2]:
prices_a[1:]

[8.9, 8.71]

In [3]:
prices_a[:-1]

[8.7, 8.9]

In [9]:
prices_a[1:]/prices_a[:-1] -1

array([ 0.02298851, -0.02134831])

In [11]:
prices = pd.DataFrame({
    'Blue' : [8.7, 8.91, 9.1, 9.23, 9.1],
    'Orange': [10.2, 10.34, 10.22, 9.98, 10.1]
})

In [12]:
prices

   Blue  Orange
0  8.70   10.20
1  8.91   10.34
2  9.10   10.22
3  9.23    9.98
4  9.10   10.10

In [13]:
prices.iloc[1:]

   Blue  Orange
1  8.91   10.34
2  9.10   10.22
3  9.23    9.98
4  9.10   10.10

In [14]:
prices.iloc[:-1]

   Blue  Orange
0  8.70   10.20
1  8.91   10.34
2  9.10   10.22
3  9.23    9.98

In [15]:
prices.iloc[1:].values/prices.iloc[:-1]-1

       Blue    Orange
0  0.024138  0.013725
1  0.021324 -0.011605
2  0.014286 -0.023483
3 -0.014085  0.012024

In [18]:
#alternative method 1
prices/prices.shift(1)-1

       Blue    Orange
0       NaN       NaN
1  0.024138  0.013725
2  0.021324 -0.011605
3  0.014286 -0.023483
4 -0.014085  0.012024

In [24]:
# alternative method 2 (by methods)
returns = prices.pct_change()
returns

       Blue    Orange
0       NaN       NaN
1  0.024138  0.013725
2  0.021324 -0.011605
3  0.014286 -0.023483
4 -0.014085  0.012024

In [25]:
returns+1

       Blue    Orange
0       NaN       NaN
1  1.024138  1.013725
2  1.021324  0.988395
3  1.014286  0.976517
4  0.985915  1.012024

In [27]:
#compounding return calculation
#copounding row by row - method 1
np.prod(returns+1) -1

Blue      0.045977
Orange   -0.009804
dtype: float64

In [30]:
#method 2
(((returns+1).prod()-1)*100).round(2)

Blue      4.60
Orange   -0.98
dtype: float64

**Annualization Calculation**

In [32]:
rm = 0.01
(1+rm)**12 -1

0.12682503013196977